<?php  

function titoliform_form_alter(&$form, $form_state, $form_id) {	

	// Pagina modifica profilo
	if ($form_id == 'profile_node_form') {		
		drupal_set_title(t('Modifica profilo'));			
		
		// Pagina creazione profilo
		if ( $form['field_nome'][0]['#default_value']['value'] == '') {
			drupal_set_title(t('Registrazione utente'));		
		}		
	}
	
	// Pagina recupero password
	if ($form_id == 'user_pass') {
		drupal_set_title(t('Recupero credenziali'));
	}
	
}

