<?php  

function titoliform_form_alter(&$form, $form_state, $form_id) {
	
	//echo "$form[name][0]<br>";	
	//print_r($form);
	//echo "Titolo inizio: $titolo<p>";

	if ($form_id == 'user_register') {
		//echo "1<br>";
		$titolo = "Registrazione profilo";
		drupal_set_title(t($titolo));		
	}

	//echo "Titolo: $titolo<p>";*/

	/*if ($form_id == 'profile_node_form') {
		//echo "2<br>";
		drupal_set_title(t('Modifica profilo')); 					
	}*/

	if ($form_id == 'user_pass') {
		drupal_set_title(t('Recupero credenziali'));
	}
	
}

function titoliform_validate($form, &$form_state) {

}
